clear all; close all; clc;

load('results/release-flickr-links-elite-1-common-1-linear-results.csv');
load('results/release-flickr-links-elite-2-common-1-linear-results.csv');
load('results/release-flickr-links-elite-3-common-1-linear-results.csv');
load('results/release-flickr-links-elite-4-common-1-linear-results.csv');
load('results/release-flickr-links-elite-5-common-1-linear-results.csv');

load('results/release-flickr-links-elite-1-common-1-log-results.csv');
load('results/release-flickr-links-elite-2-common-1-log-results.csv');
load('results/release-flickr-links-elite-3-common-1-log-results.csv');
load('results/release-flickr-links-elite-4-common-1-log-results.csv');
load('results/release-flickr-links-elite-5-common-1-log-results.csv');

load('measurements/release-flickr-links-measurements.txt');

load('results/bi-facebook-links-elite-1-common-1-linear-results.csv');
load('results/bi-facebook-links-elite-2-common-1-linear-results.csv');
load('results/bi-facebook-links-elite-3-common-1-linear-results.csv');
load('results/bi-facebook-links-elite-4-common-1-linear-results.csv');
load('results/bi-facebook-links-elite-5-common-1-linear-results.csv');

load('results/bi-facebook-links-elite-1-common-1-log-results.csv');
load('results/bi-facebook-links-elite-2-common-1-log-results.csv');
load('results/bi-facebook-links-elite-3-common-1-log-results.csv');
load('results/bi-facebook-links-elite-4-common-1-log-results.csv');
load('results/bi-facebook-links-elite-5-common-1-log-results.csv');

load('measurements/bi-facebook-links-measurements.txt');

load('results/bi-release-youtube-links-elite-1-common-1-linear-results.csv');
load('results/bi-release-youtube-links-elite-2-common-1-linear-results.csv');
load('results/bi-release-youtube-links-elite-3-common-1-linear-results.csv');
load('results/bi-release-youtube-links-elite-4-common-1-linear-results.csv');
load('results/bi-release-youtube-links-elite-5-common-1-linear-results.csv');

load('results/bi-release-youtube-links-elite-1-common-1-log-results.csv');
load('results/bi-release-youtube-links-elite-2-common-1-log-results.csv');
load('results/bi-release-youtube-links-elite-3-common-1-log-results.csv');
load('results/bi-release-youtube-links-elite-4-common-1-log-results.csv');
load('results/bi-release-youtube-links-elite-5-common-1-log-results.csv');

load('measurements/bi-release-youtube-links-measurements.txt');

load('results/bi-Cit-HepTh-elite-1-common-1-linear-results.csv');
load('results/bi-Cit-HepTh-elite-2-common-1-linear-results.csv');
load('results/bi-Cit-HepTh-elite-3-common-1-linear-results.csv');
load('results/bi-Cit-HepTh-elite-4-common-1-linear-results.csv');
load('results/bi-Cit-HepTh-elite-5-common-1-linear-results.csv');

load('results/bi-Cit-HepTh-elite-1-common-1-log-results.csv');
load('results/bi-Cit-HepTh-elite-2-common-1-log-results.csv');
load('results/bi-Cit-HepTh-elite-3-common-1-log-results.csv');
load('results/bi-Cit-HepTh-elite-4-common-1-log-results.csv');
load('results/bi-Cit-HepTh-elite-5-common-1-log-results.csv');

load('measurements/bi-Cit-HepTh-measurements.txt');

load('results/bi-soc-Epinions1-elite-1-common-1-linear-results.csv');
load('results/bi-soc-Epinions1-elite-2-common-1-linear-results.csv');
load('results/bi-soc-Epinions1-elite-3-common-1-linear-results.csv');
load('results/bi-soc-Epinions1-elite-4-common-1-linear-results.csv');
load('results/bi-soc-Epinions1-elite-5-common-1-linear-results.csv');

load('results/bi-soc-Epinions1-elite-1-common-1-log-results.csv');
load('results/bi-soc-Epinions1-elite-2-common-1-log-results.csv');
load('results/bi-soc-Epinions1-elite-3-common-1-log-results.csv');
load('results/bi-soc-Epinions1-elite-4-common-1-log-results.csv');
load('results/bi-soc-Epinions1-elite-5-common-1-log-results.csv');

load('measurements/bi-soc-Epinions1-measurements.txt');

n = bi_soc_Epinions1_measurements(1);
m = bi_soc_Epinions1_measurements(2);
%x_log_y_linear
% processResults(release_flickr_links_elite_1_common_1_log_results,...
    % 'release_flickr_links_elite_1_common_1_x_log_y_linear_results.png',...
    % 'Majority vote with elite coalition\newlineElite vote = 1, Common vote = 1\newlineflickr',...
    % 'x-log-y-linear');
% processResults(release_flickr_links_elite_2_common_1_log_results,...
    % 'release_flickr_links_elite_2_common_1_x_log_y_linear_results.png',...
    % 'Majority vote with elite coalition\newlineElite vote = 2, Common vote = 1\newlineflickr',...
    % 'x-log-y-linear');
% processResults(release_flickr_links_elite_3_common_1_log_results,...
    % 'release_flickr_links_elite_3_common_1_x_log_y_linear_results.png',...
    % 'Majority vote with elite coalition\newlineElite vote = 3, Common vote = 1\newlineflickr',...
    % 'x-log-y-linear');
% processResults(release_flickr_links_elite_4_common_1_log_results,...
    % 'release_flickr_links_elite_4_common_1_x_log_y_linear_results.png',...
    % 'Majority vote with elite coalition\newlineElite vote = 4, Common vote = 1\newlineflickr',...
    % 'x-log-y-linear');
% processResults(release_flickr_links_elite_5_common_1_log_results,...
    % 'release_flickr_links_elite_5_common_1_x_log_y_linear_results.png',...
    % 'Majority vote with elite coalition\newlineElite vote = 5, Common vote = 1\newlineflickr',...
    % 'x-log-y-linear');
	
% %log
processResults(bi_soc_Epinions1_elite_1_common_1_log_results,...
    'bi_soc_Epinions1_elite_1_common_1_log_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 1, Common vote = 1\newlineEpinions',...
    'log', n, m);
processResults(bi_soc_Epinions1_elite_2_common_1_log_results,...
    'bi_soc_Epinions1_elite_2_common_1_log_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 2, Common vote = 1\newlineEpinions',...
    'log', n, m);
processResults(bi_soc_Epinions1_elite_3_common_1_log_results,...
    'bi_soc_Epinions1_elite_3_common_1_log_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 3, Common vote = 1\newlineEpinions',...
    'log', n, m);
processResults(bi_soc_Epinions1_elite_4_common_1_log_results,...
    'bi_soc_Epinions1_elite_4_common_1_log_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 4, Common vote = 1\newlineEpinions',...
    'log', n, m);
processResults(bi_soc_Epinions1_elite_5_common_1_log_results,...
    'bi_soc_Epinions1_elite_5_common_1_log_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 5, Common vote = 1\newlineEpinions',...
    'log', n, m);
	
% %linear
processResults(bi_soc_Epinions1_elite_1_common_1_linear_results,...
    'bi_soc_Epinions1_elite_1_common_1_linear_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 1, Common vote = 1\newlineEpinions',...
    'linear', n, m);
processResults(bi_soc_Epinions1_elite_2_common_1_linear_results,...
    'bi_soc_Epinions1_elite_2_common_1_linear_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 2, Common vote = 1\newlineEpinions',...
    'linear', n, m);
processResults(bi_soc_Epinions1_elite_3_common_1_linear_results,...
    'bi_soc_Epinions1_elite_3_common_1_linear_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 3, Common vote = 1\newlineEpinions',...
    'linear', n, m);
processResults(bi_soc_Epinions1_elite_4_common_1_linear_results,...
    'bi_soc_Epinions1_elite_4_common_1_linear_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 4, Common vote = 1\newlineEpinions',...
    'linear', n, m);
processResults(bi_soc_Epinions1_elite_5_common_1_linear_results,...
    'bi_soc_Epinions1_elite_5_common_1_linear_results.png',...
    'Majority vote with elite coalition\newlineElite vote = 5, Common vote = 1\newlineEpinions',...
    'linear', n, m);