clear all; 
close all;
clc
    
networks = {...
    'slashdot',...
    'twitter',...
    'gowalla',...
    'brightkite',...
    'cit-hepph',...
    'facebook',...
    'youtube',...
    'flickr',...
    };
for i = 1:numel(networks)
    network = networks{i};
    [reversible_filenames{i}, elite_non_reversible_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search', network );
    
    [reversible_m_square_filenames{i}, elite_non_reversible_m_square_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search_elite_power', network );        

end

fig = generateReversabilityCompFigure_all( reversible_filenames, ...
        elite_non_reversible_filenames,  reversible_m_square_filenames,...
        elite_non_reversible_m_square_filenames, networks);    
set(gcf, 'color', [1 1 1]);
saveas(gcf, sprintf('reversability_all_%d%s', round(rand*1000), '.pdf'), 'pdf')