%clear all; 
close all;
%clc

networks = {...    
    'gowalla',...
    'cithepph',...
    'brightkite',...
    'enron',...
    'facebook',...
    'wikiconflict',...
    'slashdot',...
    'epinions',...
    };

num = round(rand*1000);

for i = 1:numel(networks)
    network = networks{i};
    [reversible_filenames{i}, elite_non_reversible_filenames{i}] = ...
        getFilesFromFolder(sprintf('./results-sim3/4/%s/asymptotic', network), '-'); 
    
    nodes_edges_map{i} = load(sprintf('./time/%s_nodes_edges_map.txt', network));       
    
end

generateTimeAnalysisFigureMinEliteSize(reversible_filenames,...
    nodes_edges_map, 'The power of elite over time - Reversible', networks);
set(gcf, 'color', [1 1 1]);
saveas(gcf, sprintf('min_elite_size_reversible_%d.pdf', num), 'pdf');

generateTimeAnalysisFigureMinEliteSize(elite_non_reversible_filenames,...
    nodes_edges_map, 'The power of elite over time - Elite non-reversible', networks);
set(gcf, 'color', [1 1 1]);
saveas(gcf, sprintf('min_elite_size_non_reversible_%d.pdf', num), 'pdf');