clear all; 
close all;
%clc
    
networks = {...
    'jazz',...
    'slashdot',...
    'epinions',...
    'twitter',...
    'gowalla',...
    'brightkite',...
    'cit-hepph',...
    'email',...
    'dutch',...
    'polblogs',...
    'pgp',...
    'wikitalk',...
    'flickr',...
    'facebook',...
    'youtube'
    };

for i = 1:numel(networks)
    network = networks{i};
    [reversible_filename, elite_non_reversible_filename] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search', network );
    
    [reversible_m_square_filename, elite_non_reversible_m_square_filename] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search_elite_power', network );
    
    
    fig = generateReversabilityCompFigure( reversible_filename, ...
        elite_non_reversible_filename,  reversible_m_square_filename,...
        elite_non_reversible_m_square_filename, network);    
    
%     print(fig, '-dbmp', strcat('reversability_', network, '.bmp'));
    set(gcf, 'color', [1 1 1])
%     I = getframe(gcf);    
%     imwrite(I.cdata, strcat('reversability_', network, '.png'));
    saveas(gcf, strcat('reversability_', network, '.pdf'), 'pdf')
end