% clear all; 
close all;
clc

networks = {...
%     'jazz',...
%     'slashdot',...
%     'epinions',...
%     'twitter',...
%     'gowalla',...
%     'brightkite',...
%     'cit-hepph',...
%     'email',...
%     'dutch',...
%     'polblogs',...
%     'pgp',...
%     'wikitalk',...
%     'flickr',...
    'facebook',...
    'youtube'
    };

for i = 1:numel(networks)
    network = networks{i};
    [reversible_filename, elite_non_reversible_filename] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search', network );
    
    [reversible_barabasi_filename, elite_non_reversible_barabasi_filename] = ...
        getFilesFromFolder( './results-sim3/2/barabasi/binary_search', network );
    
    [reversible_erdos_filename, elite_non_reversible_erdos_filename] = ...
        getFilesFromFolder( './results-sim3/2/erdos/binary_search', network );
    
    [reversible_m_square_filename, elite_non_reversible_m_square_filename] = ...
        getFilesFromFolder( './results-sim3/2/networks/elite=m^.5', network );
    
    [reversible_barabasi_m_square_filename, elite_non_reversible_barabasi_m_square_filename] = ...
        getFilesFromFolder( './results-sim3/2/barabasi/elite=m^.5', network );
    
    [reversible_erdos_m_square_filename, elite_non_reversible_erdos_m_square_filename] = ...
        getFilesFromFolder( './results-sim3/2/erdos/elite=m^.5', network );
    
    
    generateRealBaErCompFigure(...
        reversible_filename,...
        reversible_barabasi_filename,...
        reversible_erdos_filename,...
        reversible_m_square_filename,...
        reversible_barabasi_m_square_filename,...
        reversible_erdos_m_square_filename,...
        'Reversible');
    
    set(gcf, 'color', [1 1 1])
    I = getframe(gcf);    
    imwrite(I.cdata, strcat('realErBaComp_reversible_', network, '.png'));
    
    generateRealBaErCompFigure(elite_non_reversible_filename,...
        elite_non_reversible_barabasi_filename,...
        elite_non_reversible_erdos_filename,...
        elite_non_reversible_m_square_filename,...
        elite_non_reversible_barabasi_m_square_filename,...
        elite_non_reversible_erdos_m_square_filename,...
        '(Elite) Non-Reversible');
    
    set(gcf, 'color', [1 1 1])
    I = getframe(gcf);    
    imwrite(I.cdata, strcat('realErBaComp_elite_non_reversible_', network, '.png'));
end



