%clear all; 
close all;
%clc

networks = {...    
    'gowalla',...
    'cithepph',...
    'brightkite',...
    'enron',...
    'facebook',...
    'wikiconflict',...
    'slashdot',...
    'epinions',...
    };
num = round(rand*1000);

for i = 1:numel(networks)
    network = networks{i};
    [reversible_filenames{i}, elite_non_reversible_filenames{i}] = ...
        getFilesFromFolder(sprintf('./results-sim3/4/%s/min_power', network), '-');    
    
    
    
end

generateTimeAnalysisFigureMinPower(reversible_filenames,...
        'The power of $\sqrt{m}$-elite over time - Reversible', networks);
    set(gcf, 'color', [1 1 1]);
    saveas(gcf, sprintf('min_power_reversible_%d.pdf', num), 'pdf');
    
generateTimeAnalysisFigureMinPower(elite_non_reversible_filenames,...
        'The power of $\sqrt{m}$-elite over time - Elite non-reversible', networks);
    set(gcf, 'color', [1 1 1]);
    saveas(gcf, sprintf('min_power_elite_non_reversible_%d.pdf', num), 'pdf');