clear all;
close all;
%clc

networks = {...
    'slashdot',...
    'twitter',...
    'gowalla',...
    'brightkite',...
    'cit-hepph',...
    'facebook',...
    'youtube',...
    'flickr',...
    };

% networks = {...
%     'jazz',...
%     'epinions',...
%     'email',...
%     'dutch',...
%     'polblogs',...
%     'pgp',...
%     'wikitalk',...
%     };

for i = 1:numel(networks)
    network = networks{i};
    [reversible_filenames{i}, elite_non_reversible_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search', network );
    
    [reversible_m_square_filenames{i}, elite_non_reversible_m_square_filename{i}] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search_elite_power', network );
    
end

generatePowerOfEliteFigure(reversible_filenames,...
    reversible_m_square_filenames, 'Power of elite - Reversible');
set(gcf, 'color', [1 1 1]);
num = round(rand*1000);
saveas(gcf, sprintf('power_of_elite_reversible_%d.pdf', num), 'pdf');

generatePowerOfEliteFigure(elite_non_reversible_filenames,...
    elite_non_reversible_m_square_filename, 'Power of elite - Elite non-reversible');
set(gcf, 'color', [1 1 1]);
saveas(gcf, sprintf('power_of_elite_elite_non_reversible_%d.pdf', num), 'pdf');