clear all; 
%close all;
clc

network = 'flickr';

[reversible_filename, elite_non_reversible_filename] = ...
    getFilesFromFolder( './results-sim3/2/networks', network );

[reversible_barabasi_filename, elite_non_reversible_barabasi_filename] = ...
    getFilesFromFolder( './results-sim3/2/barabasi', network );

[reversible_erdos_filename, elite_non_reversible_erdos_filename] = ...
    getFilesFromFolder( './results-sim3/2/erdos', network );

[reversible_m_square_filename, elite_non_reversible_m_square_filename] = ...
    getFilesFromFolder( './results-sim3/2/networks/elite=m^.5', network );

[reversible_barabasi_m_square_filename, elite_non_reversible_barabasi_m_square_filename] = ...
    getFilesFromFolder( './results-sim3/2/barabasi/elite=m^.5', network );

[reversible_erdos_m_square_filename, elite_non_reversible_erdos_m_square_filename] = ...
    getFilesFromFolder( './results-sim3/2/erdos/elite=m^.5', network );


generateRealBaErCompFigure(...
    reversible_filename,...
    reversible_barabasi_filename,...
    reversible_erdos_filename,...
    reversible_m_square_filename,...
    reversible_barabasi_m_square_filename,...
    reversible_erdos_m_square_filename,...
    'Reversible');

generateRealBaErCompFigure(elite_non_reversible_filename,...
    elite_non_reversible_barabasi_filename,...
    elite_non_reversible_erdos_filename,...
    elite_non_reversible_m_square_filename,...
    elite_non_reversible_barabasi_m_square_filename,...
    elite_non_reversible_erdos_m_square_filename,...
    '(Elite) Non-Reversible');




