% clear all; 
close all;
clc

networks = {...
    'slashdot',...
    'twitter',...
    'gowalla',...
    'brightkite',...
    'cit-hepph',...
    'facebook',...
    'youtube',...
    'flickr'
    };

% networks = {...
%     'jazz',...
%     'epinions',...
%     'email',...
%     'dutch',...
%     'polblogs',...
%     'pgp',...
%     'wikitalk',...
%     };

for i = 1:numel(networks)
    network = networks{i};
    [reversible_filenames{i}, elite_non_reversible_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search', network );
    
    [reversible_barabasi_filenames{i}, elite_non_reversible_barabasi_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/barabasi/binary_search', network );
    
    [reversible_erdos_filenames{i}, elite_non_reversible_erdos_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/erdos/binary_search', network );
    
    [reversible_m_square_filenames{i}, elite_non_reversible_m_square_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/networks/binary_search_elite_power', network );
    
    [reversible_barabasi_m_square_filenames{i}, elite_non_reversible_barabasi_m_square_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/barabasi/binary_search_elite_power', network );
    
    [reversible_erdos_m_square_filenames{i}, elite_non_reversible_erdos_m_square_filenames{i}] = ...
        getFilesFromFolder( './results-sim3/2/erdos/binary_search_elite_power', network );

end

num = round(rand*1000);

generateRealBaErCompFigure(...
    reversible_filenames,...
    reversible_barabasi_filenames,...
    reversible_erdos_filenames,...
    reversible_m_square_filenames,...
    reversible_barabasi_m_square_filenames,...
    reversible_erdos_m_square_filenames,...
    'Reversible');

set(gcf, 'color', [1 1 1]);
saveas(gcf, sprintf('realErBaComp_reversible_%d.pdf', num), 'pdf');

generateRealBaErCompFigure(elite_non_reversible_filenames,...
    elite_non_reversible_barabasi_filenames,...
    elite_non_reversible_erdos_filenames,...
    elite_non_reversible_m_square_filenames,...
    elite_non_reversible_barabasi_m_square_filenames,...
    elite_non_reversible_erdos_m_square_filenames,...
    'Irreversible');

set(gcf, 'color', [1 1 1]);
saveas(gcf, sprintf('realErBaComp_elite_non_reversible_%d.pdf', num), 'pdf');




